django/blog/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^team/$', views.team, name='team'),
    url(r'^index/$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^poll/$', views.ankieta, name='ankieta'),
    url(r'^poll/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^poll/(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^poll/(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^team/(?P<pk>[0-9]+)/$', views.team_detail, name='team_detail'),
    url(r'^terminarz/team/(?P<pk>[0-9]+)/$', views.team_fixture, name='team_fixture'),
    url(r'^match/squad/(?P<pk>[0-9]+)/$', views.match, name='match'),
    url(r'^tactic/team/(?P<pk>[0-9]+)/$', views.tactic, name='tactic'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/blog/models.py
from django.db import models
from django.utils import timezone
from django.db.models import F, Case, When, Value, CharField
from django.utils.translation import ugettext as _
from django.db.models import Q, Sum
from django.shortcuts import render, get_object_or_404
from .functions import kto_wygral, podlicz_punkty, statystyki_zawodnika
from .choices import nationality_choices, position_choices

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=100)
    text = models.TextField()
    obrazek = models.ImageField(upload_to='post/', blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Team(models.Model):
    author = models.ForeignKey('auth.User')
    team = models.CharField(max_length=30)
    win_home = models.IntegerField(default=0)
    draw_home = models.IntegerField(default=0)
    lose_home = models.IntegerField(default=0)
    strzelone_home = models.IntegerField(default=0)
    stracone_home = models.IntegerField(default=0)
    points_home = models.IntegerField(default=0)

    win_away = models.IntegerField(default=0)
    draw_away = models.IntegerField(default=0)
    lose_away = models.IntegerField(default=0)
    strzelone_away = models.IntegerField(default=0)
    stracone_away = models.IntegerField(default=0)
    points_away = models.IntegerField(default=0)

    win = models.IntegerField(default=0)
    draw = models.IntegerField(default=0)
    lose = models.IntegerField(default=0)
    points = models.IntegerField(default=0)



    def save(self, *args, **kwargs):
        podlicz_punkty(self, *args, **kwargs)
        super(Team, self).save(*args, **kwargs)

    def __str__(self):
        return self.team


class Zawodnik(models.Model):
    team = models.ForeignKey(Team)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=50)
    number = models.IntegerField(default=0)
    app = models.IntegerField(default=0)
    timePlayed = models.IntegerField(default=0)
    goals = models.IntegerField(default=0)
    dateOfBirth = models.DateField(default=timezone.now)
    photo = models.ImageField(upload_to="photo/", blank=True, null=True)
    nationality = models.CharField(max_length=2, choices=nationality_choices)
    position = models.CharField(max_length=2, choices=position_choices)

    def __str__(self):
        return self.name + " " + self.surname


class Match(models.Model):
    author = models.ForeignKey('auth.User')
    team1 = models.ForeignKey(Team, null=True, related_name='team1')
    goal1 = models.IntegerField(blank=True, null=True)
    team2 = models.ForeignKey(Team, null=True, related_name='team2')
    goal2 = models.IntegerField(blank=True, null=True)
    wynik = models.CharField(default=0, max_length=400, help_text="Save to see")
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)


    def __str__(self):
        if self.goal1 is None:
            self.goal1 = ' '
        if self.goal2 is None:
            self.goal2 = ' '
        return str(self.team1) + " " + str(self.goal1) + " " + "vs" + " " + str(self.goal2)+" "+str(self.team2)


    def save(self, *args, **kwargs):
        if self.goal1 is None and self.goal2 is not None:
            self.goal1 = int(0)
            kto_wygral(self, *args, **kwargs)
        elif self.goal1 is not None and self.goal2 is None:
            self.goal2 = int(0)
            kto_wygral(self, *args, **kwargs)
        elif self.goal2 is not None and self.goal1 is not None:
            kto_wygral(self, *args, **kwargs)
        self.wynik = str(self.team1) + " " + str(self.goal1) + " " + "vs" + " " + str(self.goal2)+" "+str(self.team2)
        super(Match, self).save(*args, **kwargs)

class Sklad(models.Model):
    match = models.ForeignKey(Match)
    team1Players = models.ForeignKey(Zawodnik, blank=True, null=True, related_name='team1Players')
    goalPlayer1 = models.IntegerField(default=0)
    timePlayedP1 = models.IntegerField(default=0)
    team2Players = models.ForeignKey(Zawodnik, blank=True, null=True, related_name='team2Players')
    goalPlayer2 = models.IntegerField(default=0)
    timePlayedP2 = models.IntegerField(default=0)

    def __str__(self):
        if self.team1Players is not None and self.team2Players is not None:
            return "Dodano do skladu druzyny gospodarzy ("  + self.match.team1.team + ") " + " zawodnika: "+ self.team1Players.name + " " + self.team1Players.surname + " oraz do druzyny gosci: (" + self.match.team2.team + ")" + " zawodnika: " + self.team2Players.name + " " + self.team2Players.surname
        elif self.team1Players is not None and self.team2Players is None:
            return "Dodano do skladu druzyny gospodarzy ("  + self.match.team1.team + ") " + " zawodnika: "+ self.team1Players.name + " " + self.team1Players.surname
        elif self.team1Players is None and self.team2Players is not None:
            return "Dodano do skladu druzyny gosci: (" + self.match.team2.team + ")" + " zawodnika: " + self.team2Players.name + " " + self.team2Players.surname

    def save(self, *args, **kwargs):
        statystyki_zawodnika(self, *args, **kwargs)
        super(Sklad, self).save(*args, **kwargs)

class Tactics(models.Model):
    author = models.ForeignKey('auth.User')
    tactic = models.CharField(max_length=10000)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.created_date)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data utworzenia')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    poll = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField()

    def __str__(self):
        return self.choice_text


class Ad(models.Model):
    author = models.ForeignKey('auth.User')
    name_ad = models.CharField(max_length=50)
    link = models.URLField(max_length=200)
    button = models.ImageField(upload_to="buttons/", blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name_ad


class Video(models.Model):
    user = models.ForeignKey('auth.User')
    video_id = models.CharField(max_length=255, unique=True, null=True,
                                help_text=_("Youtube ID"))
    title = models.CharField(max_length=200, null=True, blank=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

django/blog/templates/blog/detail.html
{% extends 'blog/index.html' %}
{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock content %}

django/blog/templates/blog/footer.html
<nav class="navbar">
    <div class="container-fluid center">
        <ul class="foot-tabs">
            <li class="foot-text">
                Linki:
            <br><a class="foot" href="">Pierwszy link</a>
            <br><a class="foot" href="">Drugi link</a>
            <br><a class="foot" href="">Trzeci link</a>
            <br><a class="foot" href="">Czwarty link</a>
            </li>
            <li class="foot-text">
                Partnerzy:
            <br><a class="foot" href="">Pierwszy link</a>
            <br><a class="foot" href="">Drugi link</a>
            <br><a class="foot" href="">Trzeci link</a>
            <br><a class="foot" href="">Czwarty link</a>
            </li>
            <li class="foot-text">
                Partnerzy:
            <br><a class="foot" href="">Pierwszy link</a>
            <br><a class="foot" href="">Drugi link</a>
            <br><a class="foot" href="">Trzeci link</a>
            <br><a class="foot" href="">Czwarty link</a>
            </li>
        </ul>
    </div>

    <div class="container-fluid center">
        <ul class="foot">
        <li>All Rights Reserved.</li>
            <span class="label label-default">Default Label</span>
<span class="label label-primary">Primary Label</span>
<span class="label label-success">Success Label</span>
<span class="label label-info">Info Label</span>
<span class="label label-warning">Warning Label</span>
<span class="label label-danger">Danger Label</span>
        </ul>
    </div>
</nav>

django/blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Stronka</title>
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <![endif]-->
    <script async src="{% static "blog/js/jquery.js" %}" type="text/javascript"></script>
    <script async src="{% static "blog/js/bootstrap.js" %}" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link async href="{% static "blog/css/bootstrap.css" %}" rel="stylesheet">
    <link async href="{% static "blog/css/custom.css" %}" rel="stylesheet">
</head>


    <style>
    .header {
        background: url({% static "blog/logo.jpg" %});
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        min-height: 50px;
        font-family: fantasy;
        padding: 10px;
    }
    </style>


<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="header">
                {% include 'blog/header.html' %}
            </div>
        </div>
    </div>
     <div class="row">
        <div class="col-sm-12">
                {% include 'blog/menu.html' %}
        </div>
     </div>
    <div class="row">
      <div class="col-sm-9 col-md-9 col-lg-10">
              <div class="post">
                {% block content %}
                {% endblock content %}
              </div>
      </div>
        <div class="logowanie">
          {% include 'blog/login.html' %}
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3 col-lg-2  break">
          {% include 'blog/sidebarright.html' %}
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3 col-lg-2">
          {% include 'blog/sidebarright2.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel-footer">
                {% include 'blog/footer.html' %}
            </div>
        </div>
    </div>
</div>
<script src="{% static "blog/js/jquery-ui.js" %}"></script>
<script src="{% static "blog/js/jquery.ui.touch-punch.min.js" %}" type="text/javascript"></script>
<script>
$("document").ready(function() {
$('.logowanie').draggable({containment: 'body'});
});
  </script>
</body>
</html>

django/blog/templates/blog/login.html
<div class="loginPanel">
            {% if user.is_authenticated %}
                Zalogowany jako: <b>{{ user.username }}</b>
            {% else %}
                Nie jesteś zalogowany.
            {% endif %}</b>

          {% if user.is_authenticated %}
          <li><a href="{% url 'account_email' %}">Zmień e-mail</a></li>
          <li><a href="{% url 'account_logout' %}">Wyloguj się</a></li>
          {% else %}
          <li><a href="{% url 'account_login' %}">Zaloguj sie</a></li>
          <li><a href="{% url 'account_signup' %}">Zarejestruj sie</a></li>
          {% endif %}
</div>

django/blog/templates/blog/mecz.html
 {% extends 'blog/index.html' %}
 {% block content %}
 {% load math %}
 <div class="row">
   <div class="col-sm-12 score">
        <h1> {{match.wynik}} </h1>
   </div>
   <div class="col-sm-6">
     <div class="match">
         <h1>{{ match.team1 }}</h1>
         <!--- Goalkeepers sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team1Players.timePlayed > 45 %}
         {% if sklad.team1Players != None %}
          {% if sklad.team1Players.position = "GK" %}
          <li> <b>{{ sklad.team1Players.position }}</b>
            {{ sklad.team1Players }}
            {% if sklad.timePlayedP1 = 90 %}
            <span class="time">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.timePlayedP1 > 45 and sklad.timePlayedP1 < 90 %}
            <span class="time red">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.goalPlayer1 != 0 %}
            <span class="goal">[{{sklad.goalPlayer1}}]</span></li>
            {% endif %}
          {% endif %}
         {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Defenders sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team1Players != None %}
        {% if sklad.team1Players.timePlayed > 45 %}
          {% if sklad.team1Players.position = "DF" %}
          <li> <b>{{ sklad.team1Players.position }}</b>
            {{ sklad.team1Players }}
            {% if sklad.timePlayedP1 = 90 %}
            <span class="time">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.timePlayedP1 > 45 and sklad.timePlayedP1 < 90 %}
            <span class="time red">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.goalPlayer1 != 0 %}
            <span class="goal">[{{sklad.goalPlayer1}}]</span></li>
            {% endif %}
          {% endif %}
         {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Mclassifielders sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team1Players != None %}
        {% if sklad.team1Players.timePlayed > 45 %}
          {% if sklad.team1Players.position = "MF" %}
          <li> <b>{{ sklad.team1Players.position }}</b>
            {{ sklad.team1Players }}
            {% if sklad.timePlayedP1 = 90 %}
            <span class="time">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.timePlayedP1 > 45 and sklad.timePlayedP1 < 90 %}
            <span class="time red">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.goalPlayer1 != 0 %}
            <span class="goal">[{{sklad.goalPlayer1}}]</span></li>
            {% endif %}
          {% endif %}
         {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Forwarders sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team1Players != None %}
         {% if sklad.team1Players.timePlayed > 45 %}
          {% if sklad.team1Players.position = "FW" %}
          <li> <b>{{ sklad.team1Players.position }}</b>
            {{ sklad.team1Players }}
            {% if sklad.timePlayedP1 = 90 %}
            <span class="time">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.timePlayedP1 > 45 and sklad.timePlayedP1 < 90 %}
            <span class="time red">{{sklad.timePlayedP1}}'</span>
            {% endif %}
            {% if sklad.goalPlayer1 != 0 %}
            <span class="goal">[{{sklad.goalPlayer1}}]</span></li>
            {% endif %}
          {% endif %}
         {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Rezerwowi < 45 minut -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team1Players != None %}
         {% if sklad.team1Players.timePlayed < 45 %}
          <li> <b>{{ sklad.team1Players.position }}</b>
            {{ sklad.team1Players }}
            <span class="time green">{{ 90|roznica:sklad.timePlayedP1}}'</span>
            {% if sklad.goalPlayer1 != 0 %}
            <span class="goal">[{{ sklad.goalPlayer1}}]</span></li>
          {% endif %}
         {% endif %}
         {% endif %}
         {% endfor %}
       </div>
   </div>
   <div class="col-sm-6">
     <div class="match">
         <h1>{{ match.team2 }}</h1>
         <!--- Goalkeepers sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team2Players != None %}
         {% if sklad.team2Players.timePlayed > 45 %}
          {% if sklad.team2Players.position = "GK" %}
          <li> <b>{{ sklad.team2Players.position }}</b>
            {{ sklad.team2Players }}
            {% if sklad.timePlayedP2 = 90 %}
            <span class="time">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.timePlayedP2 > 45 and sklad.timePlayedP2 < 90 %}
            <span class="time red">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.goalPlayer2 != 0 %}
            <span class="goal">[{{sklad.goalPlayer2}}]</span></li>
            {% endif %}
          {% endif %}
         {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Defenders sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team2Players != None %}
         {% if sklad.team2Players.timePlayed > 45 %}
          {% if sklad.team2Players.position = "DF" %}
          <li> <b>{{ sklad.team2Players.position }}</b>
            {{ sklad.team2Players }}
            {% if sklad.timePlayedP2 = 90 %}
            <span class="time">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.timePlayedP2 > 45 and sklad.timePlayedP2 < 90 %}
            <span class="time red">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.goalPlayer2 != 0 %}
            <span class="goal">[{{sklad.goalPlayer2}}]</span></li>
            {% endif %}
          {% endif %}
          {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Mclassifielders sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team2Players != None %}
         {% if sklad.team2Players.timePlayed > 45 %}
          {% if sklad.team2Players.position = "MF" %}
          <li> <b>{{ sklad.team2Players.position }}</b>
            {{ sklad.team2Players }}
            {% if sklad.timePlayedP2 = 90 %}
            <span class="time">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.timePlayedP2 > 45 and sklad.timePlayedP2 < 90 %}
            <span class="time red">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.goalPlayer2 != 0 %}
            <span class="goal">[{{sklad.goalPlayer2}}]</span></li>
            {% endif %}
          {% endif %}
          {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Forwarders sorted by timePlayed -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team2Players != None %}
         {% if sklad.team2Players.timePlayed > 45 %}
          {% if sklad.team2Players.position = "FW" %}
          <li> <b>{{ sklad.team2Players.position }}</b>
            {{ sklad.team2Players }}
            {% if sklad.timePlayedP2 = 90 %}
            <span class="time">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.timePlayedP2 > 45 and sklad.timePlayedP2 < 90 %}
            <span class="time red">{{sklad.timePlayedP2}}'</span>
            {% endif %}
            {% if sklad.goalPlayer2 != 0 %}
            <span class="goal">[{{sklad.goalPlayer2}}]</span></li>
            {% endif %}
          {% endif %}
          {% endif %}
         {% endif %}
         {% endfor %}
         <!--- Rezerwowi < 45 minut -->
         {% for sklad in match.sklad_set.all|dictsortreversed:"team1Players.timePlayed" %}
         {% if sklad.team2Players != None %}
         {% if sklad.team2Players.timePlayed < 45 %}
          <li> <b>{{ sklad.team2Players.position }}</b>
            {{ sklad.team2Players }}
            <span class="time green">{{ 90|roznica:sklad.timePlayedP2}}'</span>
            {% if sklad.goalPlayer2 != 0 %}
            <span class="goal">[{{ sklad.goalPlayer2}}]</span></li>
          {% endif %}
         {% endif %}
         {% endif %}
         {% endfor %}
       </div>
   </div>
</div>
{% endblock content %}

django/blog/templates/blog/menu.html
{% load account %}
<div class="row">
    <div class="col-sm-12">
<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'post_list' %}">Menu</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'post_list' %}">Strona główna<span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tabele <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'team' %}">Ekstraklasa</a></li>
            <li><a href="">Drugi</a></li>
            <li><a href="">Trzeci</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ankiety <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'ankieta' %}">Wszystkie ankiety</a></li>
                {% if pytania_ankieta %}
                    {% for question in pytania_ankieta  %}
                        <li><a href="{% url 'detail' question.id %}">{{ question.id }}. {{ question.question_text }}</a></li>
                    {% endfor %}
                {% endif %}
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sklady <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if lista_druzyn %}
                    {% for team in lista_druzyn %}
                        <li><a href="{% url 'team_detail' pk=team.pk %}">{{ team.team }}</a></li>
                    {% endfor %}
                {% endif %}
          </ul>
        </li>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Terminarze <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if lista_druzyn %}
                    {% for team in lista_druzyn %}
                        <li><a href="{% url 'team_fixture' pk=team.pk %}">{{ team.team }}</a></li>
                    {% endfor %}
                {% endif %}
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>
</div>
</div>

django/blog/templates/blog/modal.html
{% load math %}
{% load tz %}
  <div>
  <img class="modalPhoto" src="/media/{{ dane.photo }}"/>
  <div class="modalOpis">
  <ul>
    <li>Pozycja: {{ dane.get_position_display }} </li>
    <li>Narodowość: {{ dane.get_nationality_display }}</li>
    <li>Data urodzenia: {{dane.dateOfBirth }}</li>
    <li>Wiek: {% now "Y" as current_year %}
    {{dane.dateOfBirth|date:'Y'|wiek:current_year}}</li>
    <li>Ilość rozegranych spotkań: {{ dane.app }}</li>
    <li>Ilość rozegranych minut: {{ dane.timePlayed }}</li>
    <li>Ilość strzelonych bramek: {{dane.goals }}</li>
    <li>Średnia ilość bramek na mecz: {{ dane.goals|dzielenie:dane.app }} </li>
    <li>Średnio strzela bramkę co: {{ dane.timePlayed|dzielenie:dane.goals }} minut/y</li>
  </ul>
  </div>
</div>
<div style="clear:both;"></div>

django/blog/templates/blog/sidebarright.html
<div class="row">
    <div class="col-sm-12">
        <div class="text ad">
            Reklamy:
            {% for ad in ad %}
            <ul>
                <a target=_blank href="{{ ad.link }}"> <img src="/media/{{ ad.button }}"></a>
            </ul>
             {% endfor %}
        </div>
    </div>
</div>

django/blog/templates/blog/zawodnicy.html
 {% extends 'blog/index.html' %} {% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Skład drużyny: {{ team_detail.team }}</h1>
        <table class="table table-bordered table-mini">
            <tr class="active">
                <td>Imie i nazwisko</td>
                <td>Numer</td>
                <td>Rok urodzenia</td>
                <td>Pozycja</td>
                <td>Narodowość</td>
            </tr>
            {% for dane in team_detail.zawodnik_set.all|dictsort:"surname" %}
            <tr class="tr_color">
            <td>
                <a data-toggle="modal" data-target="#{{ dane.id }}" class="link_table">{{ dane.name }} {{ dane.surname }}</a>
            </td>
            <!-- Modal -->
            <div class="modal fade" id="{{ dane.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h1 class="modal-title" id="myModalLabel">{{ dane.name }} {{ dane.surname }}</h1>
                        </div>
                        <div class="modal-body">
                              {% include 'blog/modal.html' %}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
              </div>
                <td>{{ dane.number }} </td>
                <td>{{ dane.dateOfBirth }}</td>
                <td>{{ dane.position }}</td>
                <td>{{ dane.get_nationality_display }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}